name: COMP361
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - numpy=2.2.3
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.11.11
  - python_abi=3.11
  - setuptools=75.8.0
  - sqlite=3.49.1
  - tk=8.6.13
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - xz-tools=5.6.4
  - zlib=1.3.1
  - pip:
      - pyqt6==6.8.1
      - pyqt6-qt6==6.8.2
      - pyqt6-sip==13.10.0
