name: COMP361
channel_priority: strict
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pillow
  - pyparsing
  - python-dateutil
  - setuptools
  - wheel
  - attrs
  - packaging
  - click
  - six
  - tzdata
  - tornado
  - pyqt=6  # Cross-platform GUI framework

  # Image and Compression Libraries
  - freetype
  - lcms2
  - libpng
  - libjpeg-turbo
  - openjpeg
  - brotli
  - brotli-bin
  - xz
  - zstd
  - bzip2
  - lzo
  - lz4-c

  # Math & Scientific Libraries
  - affine
  - libopenblas
  - qhull
  - icu

  # Network and Security
  - libcurl
  - libssh2
  - ca-certificates
  - certifi
  - libnghttp2

  # Data Processing
  - geos
  - geotiff
  - proj

  # Additional Libraries
  - json-c
  - libdeflate
  - libexpat
  - libffi
  - libxml2
  - sqlite
  - libspatialite
  - lerc
  - minizip
  - snappy
  - uriparser
  - munkres

  # Platform-Specific Dependencies
  - llvm-openmp  # [osx]   # Required for macOS for OpenMP support
  - libiconv     # [osx]   # Iconv for macOS
  - pthread-stubs  # [osx]

  # Python Packages from PyPI
  - pip:
      - snuggs
      - click-plugins
      - cligj
      - contourpy
