from abc import ABC
from weakref import WeakSet

class Event(ABC):
    """
    This is the super class for events generated by user.
    """


class Quit(Event):
    """
    Quit Event
    """
    def __init__(self, msg: str) -> None:
        self.msg = msg

class InitialEvent(Event):
    """
    Initial Event
    """
    def __init__(self, msg: str) -> None:
        self.msg = msg


class SimulatorEvent(Event):
    """
    Simulator Event
    """
    def __init__(self, cmd: dict[str, str], task_bar=False) -> None:
        self.cmd = cmd
        self.task_bar = task_bar

class CommandEvent(Event):
    """
    Super class of Command Event
    """
    def __init__(self, command: str) -> None:
        self.command = command


class VisualizerEvent(Event):
    """
    Visualizer Event
    """
    def __init__(self, msg: str, map_path: str) -> None:
        self.msg = msg
        self.map_path = map_path

class ActionStatusEvent(Event):
    """
    Status Event with a boolean status and message
    """
    def __init__(self, status: bool, msg: str, action_name: str, task_bar= False) -> None:
        self.status = status
        self.msg = msg
        self.action_name = action_name
        self.task_bar = task_bar


class EventManager:
    """
    An event manager that receives, store and arrange the execution of the events
    """
    def __init__(self):
        """
        idea: use a queue of event to manage the execution of the event
        when an event id received, it is stored in the eventQueue
        the Event manager will execute the event based on the
        first-come-first-serve basis
        """
        self.subscribers = WeakSet()

    def register(self, subscriber) -> None:
        """
        Register the subscriber to the event manager
        """
        self.subscribers.add(subscriber)

    def unregister(self, subscriber) -> None:
        """
        Unregister the subscriber from the event manager
        """
        self.subscribers.remove(subscriber)

    def post_event(self, event) -> None:
        """
        Post the event to all registered subscribers.
        Errors in individual subscribers are caught to avoid crashing the system.
        """
        for subscriber in self.subscribers:
            try:
                subscriber.notify(event)
            except Exception as e:
                print(f"[Warning] Event handling failed for {subscriber} with event {event}: {e}")
                for s in self.subscribers:
                    s.notify(ActionStatusEvent(False, f"Event handling failed for {subscriber} with event {event}: {e}", "Event Handling"))




